# Generated by Django 5.2.3 on 2025-06-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='URL de origem do fragmento da documentação.', max_length=1024, unique=True)),
                ('title', models.CharField(help_text='Título da página ou da seção de onde o fragmento foi extraído.', max_length=512)),
                ('content', models.TextField(help_text='O conteúdo de texto limpo do fragmento da documentação.')),
                ('django_version', models.CharField(help_text="Versão do Django a que esta documentação se refere (ex: '4.2').", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o registro foi criado.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização.')),
            ],
            options={
                'verbose_name': 'Fragmento da Documentação',
                'verbose_name_plural': 'Fragmentos da Documentação',
                'ordering': ['-created_at'],
            },
        ),
    ]
